# Generated by Django 3.1.7 on 2021-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(max_length=50),
        ),
    ]
